import os

# Ethereum
ETHEREUM_WALLET_ADDRESS = os.getenv('ETHEREUM_WALLET_ADDRESS')
ETHERSCAN_API_KEY = os.getenv('ETHERSCAN_API_KEY')
ETHERSCAN_URL_PATTERN = os.getenv('ETHERSCAN_URL_PATTERN')

# Waves
WAVES_WALLET_ADDRESS = os.getenv('WAVES_WALLET_ADDRESS')
WAVES_WALLET_PRIVATE_KEY = os.getenv('WAVES_WALLET_PRIVATE_KEY')
WAVESNODES_URL_PATTERN = os.getenv('WAVESNODES_URL_PATTERN')

# Tx processing
DISABLE_TRANSACTION_CHECK = os.getenv('DISABLE_TRANSACTION_CHECK', True)
